spring:
  application:
    name: api-company
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        serviceName: ${spring.application.name}
        healthCheckPath: /health
        healthCheckInterval: 10s
server:
  port: 8090
  
logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG